site_name: Petstore GraphQL

theme:
  name: material

nav:
  - Home: README.md
  - Example: example.md
  - Architecture: architecture.md
  - Testing: testing.md
  - Configuration: configuration.md

plugins:
  - search
