site_name: Petstore GraphQL

theme:
  name: material

nav:
  - Home: index.md
  - Example: example.md
  - Architecture: architecture.md
  - Testing: testing.md
  - Configuration: configuration.md

plugins:
  - search

markdown_extensions:
  - attr_list